FROM node:22-alpine

RUN apk add --no-cache libc6-compat

# --- ESTA ES LA PARTE CLAVE ---
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
# ------------------------------

WORKDIR /app

COPY . .

# Ahora sí instalamos turbo y las dependencias
RUN pnpm add -g turbo
RUN pnpm install

EXPOSE 3000
VOLUME [ "/app/node_modules", "/app/apps/web/node_modules" ]
CMD ["pnpm", "dev", "--filter=web"]