# Generated by Django 4.2.27 on 2026-02-04 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0118_remove_workspaceuserproperties_product_tour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueLabelEstimate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('estimate_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_estimates', to='db.estimatepoint')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_estimates', to='db.issue')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_estimates', to='db.label')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'issue_label_estimates',
            },
        ),
        migrations.AlterUniqueTogether(
            name='issuelabelestimate',
            unique_together={('issue', 'label')},
        ),
    ]
