# Generated by Codex on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0119_issueuserproperty_issuelabelestimate_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="issuelabelestimate",
            unique_together={("issue", "label", "deleted_at")},
        ),
        migrations.AddConstraint(
            model_name="issuelabelestimate",
            constraint=models.UniqueConstraint(
                fields=("issue", "label"),
                condition=models.Q(deleted_at__isnull=True),
                name="issue_label_estimate_unique_issue_label_when_deleted_at_null",
            ),
        ),
    ]
