# Generated by Django 4.2.27 on 2026-02-06 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.issue
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0120_issue_label_estimate_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueUserProperty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('filters', models.JSONField(default=plane.db.models.issue.get_default_filters)),
                ('display_filters', models.JSONField(default=plane.db.models.issue.get_default_display_filters)),
                ('display_properties', models.JSONField(default=plane.db.models.issue.get_default_display_properties)),
                ('rich_filters', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_property_user', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue User Property',
                'verbose_name_plural': 'Issue User Properties',
                'db_table': 'issue_user_properties',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='issueuserproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'project'), name='issue_user_property_unique_user_project_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='issueuserproperty',
            unique_together={('user', 'project', 'deleted_at')},
        ),
    ]
