# Generated by Django 4.2.27 on 2026-02-16 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0120_issue_label_estimate_soft_delete'),
        ('ee', '0002_issueworklog_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueworklog',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='worklogs', to='db.label'),
        ),
    ]
