# Generated by Django 4.2.22 on 2025-10-14 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0107_migrate_filters_to_rich_filters"),
        ("ee", "0051_initiativelabelassociation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Milestone Title"),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "external_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_description",
                        to="db.description",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Milestone",
                "verbose_name_plural": "Milestones",
                "db_table": "milestones",
                "ordering": ("target_date", "-created_at"),
            },
        ),
        migrations.AddField(
            model_name="projectfeature",
            name="is_automated_cycle_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectfeature",
            name="is_milestone_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="MilestoneIssue",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_milestone",
                        to="db.issue",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_issues",
                        to="ee.milestone",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Milestone Issue",
                "verbose_name_plural": "Milestone Issues",
                "db_table": "milestone_issues",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CycleSettings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Automated Cycle Title"
                    ),
                ),
                (
                    "cycle_duration",
                    models.PositiveIntegerField(
                        help_text="Duration of each cycle in days",
                        verbose_name="Cycle Duration (days)",
                    ),
                ),
                (
                    "cooldown_period",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Gap between cycles in days",
                        verbose_name="Cooldown Period (days)",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(verbose_name="First Cycle Start Date"),
                ),
                (
                    "number_of_cycles",
                    models.PositiveIntegerField(
                        help_text="How many cycles to create automatically",
                        verbose_name="Number of Future Cycles",
                    ),
                ),
                (
                    "is_auto_rollover_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically move uncompleted issues to next cycle",
                        verbose_name="Auto Rollover Issues",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cycle Settings",
                "verbose_name_plural": "Cycle Settings",
                "db_table": "cycle_settings",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AutomatedCycleLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("cycle_created", "Cycle Created"),
                            ("cycle_creation_failed", "Cycle Creation Failed"),
                            ("rollover_completed", "Rollover Completed"),
                            ("rollover_failed", "Rollover Failed"),
                            (
                                "automated_cycle_deactivated",
                                "Automated Cycle Deactivated",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, help_text="Detailed log message"),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Additional context data"),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(help_text="When the action was scheduled"),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the action was executed"
                    ),
                ),
                (
                    "automated_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creation_logs",
                        to="ee.cyclesettings",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creation_logs",
                        to="db.cycle",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Automated Cycle Log",
                "verbose_name_plural": "Automated Cycle Logs",
                "db_table": "automated_cycle_logs",
                "ordering": ("-executed_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="milestoneissue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("issue",),
                name="unique_issue_per_milestone_when_not_deleted",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="milestoneissue",
            unique_together={("issue", "deleted_at")},
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("title", "project"),
                name="unique_milestone_title_per_project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="milestone",
            unique_together={("title", "project", "deleted_at")},
        ),
        migrations.AddConstraint(
            model_name="cyclesettings",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project", "workspace"),
                name="cycle_settings_unique_project_workspace_when_deleted_at_null",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cyclesettings",
            unique_together={("project", "workspace", "deleted_at")},
        ),
        migrations.AddIndex(
            model_name="automatedcyclelog",
            index=models.Index(
                fields=["automated_cycle", "-executed_at"],
                name="automated_c_automat_4c1f68_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automatedcyclelog",
            index=models.Index(
                fields=["action", "status"], name="automated_c_action_082287_idx"
            ),
        ),
    ]
