# Generated by Django 4.2.25 on 2025-10-16 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.utils.uuid
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0107_migrate_filters_to_rich_filters'),
        ('ee', '0052_automatedcycle_milestone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name=' Intake Form Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name=' Intake Form Description')),
                ('anchor', models.CharField(db_index=True, default=plane.utils.uuid.get_anchor, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name=' Intake Form Is Active')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_forms', to='db.intake')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('work_item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_forms', to='db.issuetype')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Intake Form',
                'verbose_name_plural': 'Intake Forms',
                'db_table': 'intake_forms',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IntakeFormField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('intake_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_form_fields', to='ee.intakeform')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('work_item_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_form_fields', to='ee.issueproperty')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Intake Form Field',
                'verbose_name_plural': 'Intake Form Fields',
                'db_table': 'intake_form_fields',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='intakeformfield',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('intake_form', 'work_item_property'), name='intake_form_field_unique_intake_form_work_item_property_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='intakeformfield',
            unique_together={('intake_form', 'work_item_property')},
        ),
    ]
