# Generated by Django 4.2.24 on 2025-10-22 10:22

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def update_existing_template_category_slugs(apps, schema_editor):
    TemplateCategory = apps.get_model('ee', 'TemplateCategory')
    for category in TemplateCategory.objects.all():
        category.slug = slugify(category.name)
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0053_intakeform_intakeformfield_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatecategory',
            options={'ordering': ('sort_order', '-created_at'), 'verbose_name': 'Template Category', 'verbose_name_plural': 'Template Categories'},
        ),
        migrations.RemoveField(
            model_name='template',
            name='keywords',
        ),
        migrations.AddField(
            model_name='template',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='templatecategory',
            name='sort_order',
            field=models.FloatField(default=65535.0),
        ),
        migrations.AddField(
            model_name='templatecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=48, null=True, unique=True),
        ),
        migrations.RunPython(update_existing_template_category_slugs, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='templatecategory',
            name='slug',
            field=models.SlugField(max_length=48, unique=True),
        ),
        
    ]
