# Generated by Django 4.2.24 on 2025-10-30 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0107_migrate_filters_to_rich_filters'),
        ('ee', '0054_alter_templatecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeResponsibility',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('ASSIGNEE', 'Assignee'), ('SUBSCRIBER', 'Subscriber')], db_index=True, default='ASSIGNEE', help_text='The type of responsibility for the intake', max_length=255, verbose_name='Intake Responsibility Type')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_responsibilities', to='db.intake')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_responsibilities', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Intake Responsibility',
                'verbose_name_plural': 'Intake Responsibilities',
                'db_table': 'intake_responsibilities',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='intakeresponsibility',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('intake', 'user', 'type'), name='intake_responsibility_unique_intake_user_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='intakeresponsibility',
            unique_together={('intake', 'user', 'type', 'deleted_at')},
        ),
    ]
