# Generated by Django 4.2.26 on 2025-12-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0112_auto_20251124_0603'),
        ('ee', '0055_intakeresponsibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacememberactivitymodel',
            name='workspace_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='db.workspacemember'),
        ),
        migrations.RenameModel(
            old_name='WorkspaceMemberActivityModel',
            new_name='WorkspaceMemberActivity',
        ),

    ]
